### ISSUE TITLE
Issues with MOTD pinging

### ISSUE THREAD

**Issue by RuiNtD** [FlorianMichael/ViaFabricPlus#39]
- [ ] MCC Island's (play.mccisland.net) MOTD refuses to load, even with ViaFabricPlus's version set to default.
![image](https://user-images.githubusercontent.com/1149870/227790953-0aa11b69-785d-4a4f-ab2b-122e2ab20e11.png)
- [ ] Sometimes MOTDs show up on the wrong servers
![image](https://user-images.githubusercontent.com/1149870/227791220-ba1d5e9d-2dab-41ee-af1b-2597e664baa1.png)
  I've also seen 2b2t's MOTD on MCC Island, but I didn't get a screenshot of it.

**Comment by FlorianMichael** [comment]
Can you try to remove all mods except VFP?

**Comment by RuiNtD** [comment]
Seems these issues only occur if you have servers with a custom MC version.
![image](https://user-images.githubusercontent.com/1149870/227802013-b001dd2e-95a5-41cb-94ca-6567e8c86835.png)
Screenshot only has Fabric API and VFP. First screenshot is MCC Island.

Here's a server.dat file you can use for testing:
[servers.zip](https://github.com/FlorianMichael/ViaFabricPlus/files/11072922/servers.zip)

**Comment by FlorianMichael** [comment]
Fixed

**Comment by RuiNtD** [comment]
Still seeing the issue with VFP 2.4.8:
![image](https://user-images.githubusercontent.com/1149870/227999125-de203db9-d13b-4470-8522-6bfcea5fe27d.png)

**Comment by FlorianMichael** [comment]
Seems like a Server issue then, I know that TCP Shield doesn't always update to the new ping protocol of Minecraft

**Comment by RuiNtD** [comment]
> Seems like a Server issue then, I know that TCP Shield doesn't always update to the new ping protocol of Minecraft

\> casually not noticing the 2B2T MOTD on MCC Island
Also, all these servers give a valid MOTD without the mod.

**Comment by FlorianMichael** [comment]
Finally should have been fixed in the latest commit

**Comment by RuiNtD** [comment]
![](https://i.imgur.com/Vb2n21W.png)
🤔
